serverHost: mailserver.domain.com
proxyPort: 9090
emulatedDevice:
    defaultDeviceType: iPad
    defaultUserAgent: Apple-iPad5C3/1407.60
    defaultOs: iOS 10.3.3 14G60
    defaultFriendlyName: iPad Air 2
    defaultOsLanguage: French
    defaultModel: iPad5C3
logging:
    level: INFO
    loggers:
       "org.hibernate.validator.internal.engine.constraintvalidation.ConstraintTree": INFO
       "org.glassfish.jersey": INFO
       "javax.management.mbeanserver": INFO
    appenders:
    - type: console
    - type: file
      threshold: INFO
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      currentLogFilename: exchangeproxy.log
      archivedLogFilenamePattern: exchangeproxy-%d{yyyy-MM-dd}-%i.log.gz
      archivedFileCount: 7
      timeZone: UTC+2
      maxFileSize: 15MB